### PR TITLE
labels: map dont-land-on-v4(6).x for napi

### PR DESCRIPTION
**Pull request by MylesBorins**
napi is not on v4 or v6

### CODE REVIEW

**Comment by targos** [comment]
v4.x is duplicated everywhere

**Comment by MylesBorins** [comment]
oops 😅

**Comment by phillipj** [comment]
👍 

FYI the bot automagically re-deploys when landing commits to master, so however has access to the merge button, can also push changes to production.

**Comment by mscdex** [comment]
The tests are currently failing after this change. The n-api tests need to be updated...

**Pull request merged**
