### PR TITLE
travis: improve logging, handle more states, and make the retries configurable

### PR DESCRIPTION
**Pull request by joyeecheung**
This helped me when debugging the setup of node-core-utils. Also I think the number of retries is too high, 20 (10mins) should already be enough.

### CODE REVIEW

**Comment by joyeecheung** [comment]
Hmm, just looked into https://travis-ci.org/nodejs/llnode/jobs/303007637 , and I think 30min is probably a more suitable default.

**Comment by joyeecheung** [comment]
Just looked into https://github.com/nodejs/llnode/pull/148 a bit, turns out we don't handle the `errored` and `canceled` states so if a Travis build times out (stalled), the bot won't be able to update the status properly. I've added handling for these two.

**Comment by phillipj** [comment]
IIRC the many retries was set after seeing how long some of the docker-node builds run. For all other projects, that many retries is way too many. If that's still the case for docker-node I don't know.

**Comment by joyeecheung** [comment]
@phillipj In that case we can probably make a per-repo map for retries and go over their recent Travis builds for a reasonable value? And fallback to a smaller default value for most repos

**Comment by joyeecheung** [comment]
@phillipj OK, I've made the configuration a map and added tests for both `pollTravis.js` and `display-travis-status.js`, PTAL

**Comment by phillipj** [comment]
You've got enough access to merge this yourself, right? ..it'll get deployed to production immediately 🚀

**Comment by joyeecheung** [comment]
@phillipj Merged, thanks!

**Pull request merged**
