### PR TITLE
labels: prevent new labels being created

### PR DESCRIPTION
**Pull request by phillipj**
As @jasnell reported in #58, the bot (unexpectedly) creates new repo labels once in a while. These changes prevents that from happening, by checking which labels already exists in the repo, before adding labels to PRs.

Closes https://github.com/nodejs/github-bot/issues/58

### CODE REVIEW

**Comment by phillipj** [comment]
@nodejs/github-bot anyone willing to approve and share the blame on this one?

**Comment by Fishrock123** [comment]
Didn't we originally do this? I have a recollection of it.

**Comment by phillipj** [comment]
Earlier we fetched which labels were already added to a PR before adding
additional resolved labels, assume that's what you're referring to.

This is not related, as this ensure *new repo labels* aren't created in the
node repo. As @jasnell discovered, the bot might end up creating completely
new labels that doesn't already exist, cause a PR has created a new file in
the lib-directory, e.g lib/mapproxy.js as the PR he mentioned.

**Comment by Fishrock123** [comment]
Oh right. Do we need to do this for every check, or can we do it like.. once every hour?

**Comment by phillipj** [comment]
Good idea, once an hour should be sufficient. I'll fix

**Comment by phillipj** [comment]
Long overdue, but I just pushed cache w/1 hour expiry for the existing repo labels as suggested. 

PTAL

**Comment by phillipj** [comment]
@nodejs/github-bot this has stalled a bit, but I'll merge this within a day or two if there's no more comments or objections

**Pull request merged**
