### PR TITLE
labels: stricter version match in base branch

### PR DESCRIPTION
**Pull request by phillipj**
Minor adjustment to the regex matching the base branch a PR is targeted against.

Refs https://github.com/nodejs/github-bot/pull/55#discussion_r77553358

/cc @Fishrock123

### CODE REVIEW

**Comment by Starefossen** [comment]
**Before:**

screen shot 2016-09-05 at 22 31 45

**After:**

screen shot 2016-09-05 at 22 31 57

**Comment by mscdex** [comment]
I'm +0/leaning more towards -1 on this. What situation could arise where the current regexp would not match correctly? If anything I could see other version-specific branch suffixes, which would mean more work in maintaining the regexp. \*shrug\*

**Comment by Fishrock123** [comment]
I would prefer this, since it's possible that otherwise it may match branches that are say, more specific and may create new labels unwarrented.

**Comment by mscdex** [comment]
Release proposals have either been starting with `'proposal-'` or they are more specific in the version (e.g. `'v6.1.1-proposal'` whereas the current regexp would only match at most `'v6.1-'`. In fact, once v0.10/v0.12 are no longer, we can remove the second digit check altogether and at that point it should be *even less* of a problem since it will only look for '.x'.

**Comment by phillipj** [comment]
Although not too opinionated about this, in the case of having more explicit code, I'm leaning towards +1 on merging this.

Regex isn't everyones favorite lunch, adding the `-staging` prefix makes it easier to grasp at first glance.

**Comment by phillipj** [comment]
As far as I see, in sum the votes leaned slightly towards merging this, so here it goes to close this stalled PR.

**Pull request merged**
