### PR TITLE
travis: add nan, llnode and node-core-utils

### PR DESCRIPTION
**Pull request by joyeecheung**
This enables travis intergrations to repos that need it that I am aware of.

cc @phillipj

### CODE REVIEW

**Comment by joyeecheung** [comment]
I don't think we have the equivalent for appveyor here, nan and node-core-utils would need that as well. I can try to implement one.

**Comment by phillipj** [comment]
@Fishrock123 are you willing to temporarily open up for Travis and adding the necessary webhooks to these repos? If so, adding the github-bot would also be very nice!

**Comment by joyeecheung** [comment]
Added core-validate-commit as well.

@phillipj I can add the webhooks but I cannot get the Travis token under the nodejs account..anyone knows how to get those?

**Comment by phillipj** [comment]
@joyeecheung hm, I wondering if Travis has been connected to @Fishrock123's github.com account?

Me + some others in the @nodejs/build group can get a hold of the secret needed to setup the webhook from github.com -> github-bot when needed.

**Comment by Fishrock123** [comment]
It probably has been yeah

**Comment by Fishrock123** [comment]
Idk anything about travis really so... any ideas?

**Comment by Fishrock123** [comment]
To be honest, I don't think I can even check without enabling access to the org, is that clear to do now?

**Comment by rvagg** [comment]
the travis token that the bot has isn't mine or @Fishrock123's, we've just confirmed that

**Comment by joyeecheung** [comment]
I think to enable it we just need to configure this webhook, which can be added by searching travis on the "Integration & service" setting. 

screen shot 2017-11-14 at 9 07 08 am

The "user" should be "nodejs" and the token should be on the profile page of the nodejs travis account, similar to this one

screen shot 2017-11-14 at 9 08 35 am

> the travis token that the bot has isn't mine or @Fishrock123's, we've just confirmed that

@rvagg I think the token the bot has is the token under the Node.js account? https://travis-ci.org/nodejs

**Comment by joyeecheung** [comment]
Also, somehow node-core-utils and llnode have been able to send PR and push event to Travis without configuring the service hooks, but I guess reconfigure the hooks wouldn't hurt.

**Comment by joyeecheung** [comment]
Hmmm..I looked into the setting of the nodejs.org repo and I think it actually works like this:

1. Github sends PR/Push events to both Travis and the github bot's webhook. Somehow it doesn't have to send events to the nodejs Travis account, for example, the nodejs.org repo is linked to Fishrock123 's account, llnode is linked to indutny's account, and node-core-utils isn't even linked to anyone's account. As long as there is that hook and you've got travis.yml in your repo, and the travis page of that repo (e.g. https://travis-ci.org/nodejs/node-core-utils) seem to be working, the Travis end is hooked up with the right owner and the right repo.
2. The bot would start to poll PR status from Travis after receiving the event, and update the build status.

So my guess is, if we merge this PR, and configure the github bot hook for each repo, at least the bot will start to update the build status for llnode, node-core-utils. To configure the github bot hook, all we need is `GITHUB_WEBHOOK_SECRET` described in the github bot's README.

**Comment by phillipj** [comment]
Totally fine by me to add the necessary github-bot webhook to see if that's enough.

The `GITHUB_WEBHOOK_SECRET` secret is in our secrets repo. Ping me on IRC or someone else in the Build WG's infra group to get a hold of it.

**Comment by joyeecheung** [comment]
@phillipj @rvagg  I have tried to configure a webhook for node-core-utils and it seem to be working:

```
Connection: keep-alive
Content-Length: 0
Date: Thu, 16 Nov 2017 05:02:55 GMT
X-Powered-By: Express
X-Request-Id: a50ea40d-5e8c-44c3-aeb7-aa94a5b5d202
```

I would need to merge this request so the bot would actually start to poll the build status instead of ignoring it. Can I merge this now?

**Comment by joyeecheung** [comment]
Also, will the bot redeploy itself automatically after this has been merged?

**Comment by rvagg** [comment]
merges to master should trigger a redeploy of the bot on its server

**Comment by phillipj** [comment]
Yepp, that's correct.

That flow works like this:

1. Webhook in this repo makes github.com sends a request to the github-bot server
2. Webhook request is received by [github-webhook](https://github.com/rvagg/github-webhook) with a custom [github-bot .json-config](https://github.com/nodejs/build/blob/master/setup/github-bot/resources/github-bot-deploy-webhook.json)
3. If commit(s) landed in master, the redeploy script is executed: redeploy: https://github.com/nodejs/build/blob/master/setup/github-bot/resources/deploy-github-bot.sh

**Comment by joyeecheung** [comment]
@rvagg @phillipj I went ahead and merged this PR, let's see if it works properly

**Pull request merged**
