### PR TITLE
update github package to 12.x

### PR DESCRIPTION
**Pull request by Trott**
This eliminates a "high' (risk? priority? something else?) warning that
comes up with `npm audit`. There are still other deps that need updating
but this is probably the big one and doing it as incrementally as
possible while still eliminating that red "high" warning.

### CODE REVIEW

**Comment by targos** [comment]
Nit in commit message: 12.x

**Comment by Trott** [comment]
@targos Whoops, thanks! Fixed in the commit message and also in the PR title.

**Comment by maclover7** [comment]
Will merge/deploy early this week if no one else gets to it

**Comment by maclover7** [comment]
Merged + deployed

**Pull request merged**
