### PR TITLE
labels: add url-whatwg labels for WHATWG URL PRs

### PR DESCRIPTION
**Pull request by joyeecheung**
Ref: https://github.com/nodejs/node/issues/10625

### CODE REVIEW

**Comment by targos** [comment]
Can you also change line 24 for the C++ files?

**Comment by targos** [comment]
Maybe we should stop labeling them `url` too. /cc @jasnell

**Comment by joyeecheung** [comment]
@targos I'm +1 on stop labeling them `url`. Just see what others think.

**Comment by mscdex** [comment]
Yes, I would definitely say one label or the other. It makes it much more explicit. Also that way if some change/issue should affect both implementations, we can use both labels and it will be clear/make sense.

**Comment by joyeecheung** [comment]
Updated to remove the `url` labels.

**Comment by mscdex** [comment]
LGTM

**Comment by phillipj** [comment]
Thanks! This is live 🚀

**Pull request merged**
