### PR TITLE
🎉 Delete Travis polling code in favor of Travis CI GitHub app 🎉

### PR DESCRIPTION
**Pull request by phillipj**
We have recently found that we can enable Travis CI per repo with the Travis CI GitHub app, rather than the old GitHub Service that required organization wide private access, which the nodejs organization didn't want to provide.

Since using the GitHub app per repo instead, there is no need for this bot to do any Travis CI polling anymore -- hoooray!

Before merging this we have to enable install the Travis CI app on these repos:
- [x] [citgm](https://github.com/nodejs/citgm)
- [x] [core-validate-commit](https://github.com/nodejs/core-validate-commit)
- [x] [docker-node](https://github.com/nodejs/docker-node)
- [x] [github-bot](https://github.com/nodejs/github-bot)
- [x] [i18n](https://github.com/nodejs/i18n)
- [x] [llnode](https://github.com/nodejs/llnode)
- [x] [nan](https://github.com/nodejs/nan)
- [x] [node-core-utils](https://github.com/nodejs/node-core-utils)
- [x] [nodejs.org](https://github.com/nodejs/nodejs.org)
- [x] [readable-stream](https://github.com/nodejs/readable-stream)
- [x] [string_decoder](https://github.com/nodejs/string_decoder)

### CODE REVIEW

**Comment by phillipj** [comment]
@Trott how did you install the GitHub app for i18n? I've tried digging into this repo's Settings, but haven't found the list of GitHub apps to install 🤷‍♀️

**Comment by targos** [comment]
@phillipj AFAIK it's something that only org owners can do. I can activate the app for all the repos that you listed above.

**Comment by targos** [comment]
@phillipj done!

**Comment by phillipj** [comment]
@targos awesome, much appreciated!

That means this is ready to be merged as soon as someone had a look at the changes.

/cc @nodejs/github-bot

**Comment by joyeecheung** [comment]
@phillipj The GitHub App is configured through the organization setting instead of the repo setting.

I think @Trott tried to see if Travis can be kicked off automatically after the app is installed but we could not find anything in the Travis UI. Have you managed to find a successful CI run triggered by the app? @Trott

**Comment by joyeecheung** [comment]
So, I experimented with the https://github.com/TestOrgPleaseIgnore/test-travis-app repo:

1. I created the test-travis-app repo
2. I installed the Travis CI app from the marketplace into the TestOrgPleaseIgnore and only granted access to test-travis-app.
3. I added `.travis.yml` to that repo and pushed to master
4. A few minutes later the CI was triggered successfully: https://travis-ci.com/TestOrgPleaseIgnore/test-travis-app

**Comment by joyeecheung** [comment]
screen shot 2018-06-12 at 6 59 44 pm
screen shot 2018-06-12 at 6 59 33 pm

I noticed there is a difference in the repo's app setting page

**Comment by targos** [comment]
There seems to be an issue with this specific repo. Here is the nodejs dashboard on https://travis-ci.com/nodejs:

image

**Comment by joyeecheung** [comment]
Oh, I think this repo has not been added to the list of repo that Travis has access to. I have added it now.

screen shot 2018-06-12 at 7 03 17 pm

**Comment by joyeecheung** [comment]
@phillipj Can you try force pushing again?

**Comment by targos** [comment]
Ah lol, this repo wasn't listed in the OP so I didn't add it :)

**Comment by targos** [comment]
Can we delete the service now?

**Comment by phillipj** [comment]
> Ah lol, this repo wasn't listed in the OP so I didn't add it :)

Ohhh 🤦‍♂️ Sorry for the confusion, I haven't practised my telepathy sense in a while!

Still no signs of life after force pushing again. I'll try and delete the service like @targos mention, to see if that has anything to do with it.

**Comment by phillipj** [comment]
Nehhh still nothing I'm afraid :/

Just in case this is an issue on this particular repo, do any of you have other repos you can verify that replacing the service (and therefore the github-bot) with the Travis CI GitHub app works as expected?

**Comment by targos** [comment]
I think this is the problem:

image

The GitHub app works only on travis-ci.com. Because this repo was already using travis-ci.org and hasn't been migrated yet, it doesn't work.
See https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

**Comment by joyeecheung** [comment]
> The option to migrate to travis-ci.com for active open source repositories that were always open source will come soon.

So I guess we can only wait until then..?

**Comment by phillipj** [comment]
Found this while clicking through Travis CI docs:

> Repositories may also be migrated without their build history or build settings (including environment variables) immediately. Please contact support support@travis-ci.com and include “Repository Migration” somewhere in the subject line, and the name of the repository in your email.

I'd personally say its more beneficial for us to migrate ASAP rather than waiting in hopes the Travis crew fixes migration of history and settings. If more of you agree, we might consider sending a list of repo names to the email above?

**Comment by phillipj** [comment]
With three thumbs up on my previous comment, I'm sending Travis an email to hear if they can help us out.

**Comment by non-binary** [comment]
Hello, this is Luna from Travis CI's support team. I followed-up with @phillipj's email. I asked for some clarification but once you follow-up we'll be able to proceed with the migration. Looking forward to hearing from you! Thanks!

**Comment by phillipj** [comment]
Confirmed we wanted the entire list of repos in OP to be migrated.

**Comment by non-binary** [comment]
Thank you for following-up. I've gone ahead and migrated those repositories.

**Comment by phillipj** [comment]
That did the trick, Travis CI is now working with the GitHub app in place.

Much appreciated @non-binary!

**Comment by phillipj** [comment]
Seeing that the Travis CI app also works as expected in another repo (https://github.com/nodejs/node-core-utils/pull/255) it looks like we're ready to land this PR to stop the github-bot from posting the same Travis updates to PRs.

**Comment by joyeecheung** [comment]
@phillipj We should delete the web hooks first otherwise there will be a bunch of 404's in the hooks

**Comment by phillipj** [comment]
@joyeecheung good point 👍 

This is where we need to delete the webhook against `http://github-bot.nodejs.org:3333`:

- [ ] [citgm](https://github.com/nodejs/citgm)
- [ ] [core-validate-commit](https://github.com/nodejs/core-validate-commit)
- [ ] [docker-node](https://github.com/nodejs/docker-node)
- [x] [github-bot](https://github.com/nodejs/github-bot)
- [ ] [i18n](https://github.com/nodejs/i18n)
- [ ] [llnode](https://github.com/nodejs/llnode)
- [ ] [nan](https://github.com/nodejs/nan)
- [ ] [node-core-utils](https://github.com/nodejs/node-core-utils)
- [x] [nodejs.org](https://github.com/nodejs/nodejs.org)
- [ ] [readable-stream](https://github.com/nodejs/readable-stream)
- [ ] [string_decoder](https://github.com/nodejs/string_decoder)

*P.S. I've already deleted a couple of webhook where I had permissions to do so.*

**Comment by joyeecheung** [comment]
Should we ask the owners first in case there are any special settings in their hooks?

**Comment by joyeecheung** [comment]
I deleted the hooks of node-core-utils, llnode and core-validate-commit because I know they are not going to need it

**Comment by joyeecheung** [comment]
cc @rvagg @zeke @PeterDaveHello @MylesBorins @mcollina regarding deleting the webhooks of the github bot in favor of github apps

**Comment by mcollina** [comment]
Good for me, I’m on vacation until the 24th. Feel free to do it, or I’ll do it when I get back.

**Comment by rvagg** [comment]
lgtm! make it happen, great news!

**Comment by zeke** [comment]
screen shot 2018-06-17 at 9 11 05 pm

**Comment by LaurentGoderre** [comment]
@chorrel I removed the old integration

**Comment by joyeecheung** [comment]
I went ahead and deleted all the remaining webhooks and service integrations. If any project comes back needing those we can always revert, but I doubt if that's necessary.

This PR should be safe to merge now.

**Comment by LaurentGoderre** [comment]
@non-binary this change did mess up our secured var for the github bot access token here: https://github.com/nodejs/docker-node/blob/master/.travis.yml#L79 would it be possible to add that token to Travis.com UI instead of having it here?

**Comment by non-binary** [comment]
Since we've effectively created a _new_ repository for all of the ones that were migrated, any encrypted variables are no longer usable and have to be re-encrypted and pushed to the repository again. Or as you mentioned, you /could/ remove it from your .travis.yml file and add that token via the travis-ci UI.

**Comment by non-binary** [comment]
However, as we mentioned in the emails, no build/project settings (not defined by the .travis.yml file) were migrated to travis-ci.com along with no build history and encrypted variables becoming invalid.

**Comment by LaurentGoderre** [comment]
I woukd change it but I do not have the token for the bot.

**Comment by non-binary** [comment]
It would have to be reset then, unfortunately.

**Comment by LaurentGoderre** [comment]
@non-binary we are using the Node Bot and if I remember correctly, the same token is used everywhere

**Comment by LaurentGoderre** [comment]
Last time @rvagg provided the encrypted token

**Comment by non-binary** [comment]
Yeah, the key needs to be re-encrypted. There's no way around that, unfortunately.

**Comment by phillipj** [comment]
@LaurentGoderre could you verify it I created encrypted this correctly?

```
  secure: "XjaE72aIC1hojGF8fKJNtePpxIM6s9Tjc69/RQ5WKlblCT67Ca2bePQoLDrmEiZmqf7iw1z0hSZuboS12KQrj2kFMagtace/br8pk55gHYM6v4sND6CNIcQYrtY/PVPOss8TJmnWkfLBu/aACVfht7rK6Jycdmj0XL7mM5pKghs="
```

**Comment by phillipj** [comment]
Thanks all for reviews and help changing the repo settings!

I'm merging this now, any new issues discovered can should probably get their own issues in this repo or whichever repo it relates to.

**Pull request merged**
