### PR TITLE
jenkins: add support for libuv jenkins jobs

### PR DESCRIPTION
**Pull request by maclover7**
cc @joyeecheung, would you be able to add `nodejs/bots` as collaborators in `libuv/libuv`?

### CODE REVIEW

**Comment by joyeecheung** [comment]
@maclover7 No I am afraid, maybe @bnoordhuis ?

**Comment by bnoordhuis** [comment]
I can, but why does the bot (plural?) need write access?

**Comment by maclover7** [comment]
@bnoordhuis I'm working on having the libuv jenkins jobs push statuses to PRs (like we have in nodejs/node and other repos), and the way GitHub permissions work mean that write access / being a "collaborator" is required

**Comment by bnoordhuis** [comment]
@maclover7 Sorry for the delay, missed the notification.  Instead of full-blown collaborator status, wouldn't OAuth scopes work?

**Comment by maclover7** [comment]
@bnoordhuis hmm, we ran into the same problem with http-parser (https://github.com/nodejs/build/issues/986), and we needed to upgrade the bots to collaborator status in order for it to work. It seems like this is the only solution right now to the issue

**Comment by phillipj** [comment]
Is it still interesting to merge this?

**Comment by phillipj** [comment]
@maclover7 should this still be considered for merging and production rollout, or closed for now?

**Comment by phillipj** [comment]
Closing this for now due to lack of activity.

**Pull request closed without merging**
