### PR TITLE
scripts: new attempt-backport script for PRs

### PR DESCRIPTION
**Pull request by Fishrock123**
This is a script to automatically check if PRs can cleanly land on staging branches in the node repo.

I've been using https://github.com/TestOrgPleaseIgnore/node/pull/29 and https://github.com/TestOrgPleaseIgnore/node/pull/30 to test it and it seems to be working fine now.

This is however a first iteration and I'm sure it can be improved lots.

cc @nodejs/github-bot & @TheAlphaNerd 

Edit: some unresolved questions/issues:

- Should it unlabel if the PR later passes?

### CODE REVIEW

**Comment by phillipj** [comment]
A little more use of the bunyan logger, *really* valuable for doing post-mortem on PRs in production. See [./lib/node-repo.js](https://github.com/nodejs/github-bot/blob/master/lib/node-repo.js) for inspiration. Other than that it looks good enough to test live IMO 👍

Couple of notes for future improvements:

- Some tests would be nice to ensure we don't break this later
- Put `queue` outside of process memory too handle redeploys

The latter is already an issue, and might be subject to a bigger discussion. E.g. for the Travis build poller ([./lib/pollTravis.js](https://github.com/nodejs/github-bot/blob/master/lib/pollTravis.js)) where a redeploy could easily make inline status on a PR stall for eternity.

**Comment by Fishrock123** [comment]
> where a redeploy could easily make inline status on a PR stall for eternity.

Definitely a bug, but pushing anything to the PR branch will unblock that.

**Comment by phillipj** [comment]
> Definitely a bug, but pushing anything to the PR branch will unblock that.

Definitely, tho I assume not many contributors would know that.

**Comment by Fishrock123** [comment]
Updated and I tried to get it working at https://github.com/TestOrgPleaseIgnore/node/pull/31 but I wasn't able to get the new label removal working?

I have no idea how to test this, there are so many (necessary) moving parts. 😓

**Comment by phillipj** [comment]
Yeah I've noticed that as well, it's generally quite painful to test much
of what the bot is doing. The test code quickly gets more complex than the
actual source code 😕

**Comment by phillipj** [comment]
Should `$NODE_REPO_DIR` be an empty directory, or should the node repo already be cloned into that directory? I might get that setup in the ansible playbook before merging/deploying this.

**Comment by Fishrock123** [comment]
@phillipj it will need to be a github clone.

I thought of adding cloning logic into this but decided against it.

**Comment by Fishrock123** [comment]
Looping @mscdex's comment (https://github.com/nodejs/github-bot/issues/77#issuecomment-254644413) from the original thread which I somehow missed:

> Why use the `lts-watch-*` labels? Shouldn't those be added by users whether there are merge conflicts or not?

> Also, how would you know which labels should be added (which branches to test), unless you mean to try all branches that are not specifically excluded via `do-not-land-on-*` labels?

> Another issue is how would you keep the labels up-to-date? If someone hasn't updated their PR/branch in awhile, there could be merge conflicts at some point.

> If we stick with labels, maybe a new set of labels would be best? Like `lands-cleanly-on-*` or something?

> Is it possible to have a webhook like Travis and other services that shows the information at the bottom of the PR? If so, would that be better than labels?

Thoughts everyone?

**Comment by TheAlphaNerd** [comment]
I think we should stick with `lts-watch`. As the primary user of them at this time what I mostly care about is getting rid of unlabelled commits. People are pretty good at knowing that a commit is not properly labelled, and every commit is going to be audited one more time before it is backported. Adding an extra label is just another step that we will have to add to the auditing process.

**Comment by phillipj** [comment]
> I thought of adding cloning logic into this but decided against it.

@Fishrock123 sounds good. I'll be able to fix what's needed in the [bot's ansible playbook](https://github.com/nodejs/build/blob/master/setup/github-bot/ansible-playbook.yaml), so we're sure the server running the bot, has the repo checked out and gets `$NODE_REPO_DIR` set.

**Comment by Fishrock123** [comment]
@phillipj what's your thoughts on moving this forward? Should I just try to test it more?

**Comment by phillipj** [comment]
@Fishrock123 mainly getting some feedback on https://github.com/nodejs/build/issues/531, otherwise it LGTM.

After that, if you feel confident enough to test it on the actual node repo, I'm totally fine with that. Just got auto deploy upon merge to master working here, so you'll be able to deploy this yourself when you feel like it.

**Comment by phillipj** [comment]
@Fishrock123 it's ready -- the bot server now has the nodejs/node repo cloned and `$NODE_REPO_DIR` set to the repo directory

**Comment by phillipj** [comment]
Awesome, really looking forward to seeing this in action! 😃

**Comment by Fishrock123** [comment]
https://github.com/nodejs/node/pull/9648 appeared to be a case where the script failed prematurely because I was pointing to the wrong git remote (`upstream`) as it were on my machine.

https://github.com/nodejs/github-bot/commit/187cbd866f91e66145eab800e2e1ce17919825ca should fix that by running git commands against `origin`.

**Comment by mscdex** [comment]
I think having the bot applying the `dont-land-on-*` labels is a bit of a misnomer. My understanding of those labels is that they indicate *intention*, not whether the PR can currently be backported cleanly or not.

I think a different set of labels should be used by the bot, but the problem with that is that we're already hitting the 100 label ceiling (this is a separate issue that needs discussion too, because not everyone is aware of it).

**Comment by Fishrock123** [comment]
> I think having the bot applying the `dont-land-on-*` labels is a bit of a misnomer. My understanding of those labels is that they indicate *intention*, not whether the PR can currently be backported cleanly or not.

We directly check these labels as part of the release process, along with `semver-*`. They already do not just indicate intention, they are used as a hard stop measure for PRs that should not land to the specified branch.

**Comment by Fishrock123** [comment]
something's still not right: https://github.com/nodejs/node/pull/9472

**Comment by Fishrock123** [comment]
Another: https://github.com/nodejs/node/pull/9637

https://github.com/nodejs/github-bot/commit/015096fa2813e4b23fb9b02866c6ab5d9c53a00f - disabling for now, I clearly don't have something right still, although it got further I'll need more debug output from here on.

**Comment by phillipj** [comment]
Ping me if you need some help debugging on the bot server, e.g. do a clean checkout of the node repo again.

**Pull request merged**
