### PR TITLE
feat: add `needs-ci` label

### PR DESCRIPTION
**Pull request by aduh95**
Make the bot add a `needs-ci` label to all PRs that make changes to files that affects the `node` binary.

Refs: https://github.com/nodejs/node/pull/37308

### CODE REVIEW

**Comment by phillipj** [comment]
Ref your https://github.com/nodejs/node/pull/37308#issuecomment-777487995 about TSC consensus, I'll hold on reviewing this for now. Shout when there's news from TSC 😄

**Comment by aduh95** [comment]
https://github.com/nodejs/node/pull/37308#issuecomment-777487995 has landed :)

**Review by mmarchini — APPROVED** [review]
We should really move this to an Action 😅

**Comment by phillipj** [comment]
> We should really move this to an Action 😅

Without a doubt.

**Pull request merged**
